version: 1
accounts:
  - name: alice
    address: cosmos1ad4d3vyx6rdvqutugz4qvwp7zvldrjstr25h7u
    coins: ["20000token", "200000000stake"]
validators:
  - name: alice
    bonded: "100000000stake"
genesis:
  app_state:
    bank:
      denom_metadata:
      - base: uspn
        denom_units:
        - aliases:
          - microspn
          denom: uspn
          exponent: "0"
        - aliases:
          - millispn
          denom: mspn
          exponent: "3"
        - denom: spn
          exponent: "6"
        description: The native staking token of Starport Network
        display: spn
        name: Starport Network
        symbol: SPN
client:
  openapi:
    path: "docs/static/openapi.yml"
  typescript:
    path: "ts-client"
  vuex:
    path: "vue/src/store"
faucet:
  name: bob
  coins: ["5token", "100000stake"]
