version: 1
accounts:
  - name: alice
    address: spnt4jkut0yfnsmqle9vxk3adfwwm9vj9gsj98vqf
    coins: ["20000token", "200000000stake"]
validators:
  - name: alice
    bonded: "100000000stake"
client:
  openapi:
    path: "docs/static/openapi.yml"
  typescript:
    path: "ts-client"
  vuex:
    path: "vue/src/store"
faucet:
  name: bob
  coins: ["5token", "100000stake"]
